version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - /app/vendor
      - .:/app
    depends_on:
      - db

  db:
    image: amd64/mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  redis:
    image: redis
    ports:
      - 6379:6379
